# Generated by Django 5.0.6 on 2024-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/images/default.avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
