# Generated by Django 5.0.6 on 2024-07-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/images/default_avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
