# Generated by Django 5.0.6 on 2024-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0004_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
