# Generated by Django 5.0.6 on 2024-11-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_system', '0006_alter_post_content_alter_post_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_published',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_published',)},
        ),
    ]
